### ISSUE TITLE
Rails 5.1 deprecation error about original_exception

### ISSUE THREAD

**Issue by joevandyk** [qertoip/transaction_isolation#5]
```
DEPRECATION WARNING: Passing #original_exception is deprecated and has no effect. Exceptions will automatically capture the original exception.

gems/transaction_isolation-1.0.3/lib/transaction_isolation/active_record/connection_adapters/mysql2_adapter.rb:57:in `new'
gems/transaction_isolation-1.0.3/lib/transaction_isolation/active_record/connection_adapters/mysql2_adapter.rb:57:in `translate_exception_with_transaction_isolation_conflict'
gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:577:in `translate_exception_class'
gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:592:in `rescue in log'
gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:590:in `log'
gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `execute'
gems/activerecord-5.0.6/lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `execute'
gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:225:in `execute_and_free'
gems/activerecord-5.0.6/lib/active_record/connection_adapters/mysql/database_statements.rb:48:in `exec_delete'
gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:140:in `delete'
gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `delete'
gems/activerecord-5.0.6/lib/active_record/relation.rb:546:in `delete_all'
```

**Comment by joevandyk** [comment]
I'm not using this gem directly, I'm using transaction_retry.

**Comment by kirillplatonov** [comment]
This issue already fixed in master. @qertoip could you please release the new version?

**Comment by caspark** [comment]
@qertoip Any chance you can release master as e.g. 1.0.5 to pick up PR #6 ? :)

We're stuck on a fork until then, and we'd rather not be on any forks!

**Comment by felixvf** [comment]
This bites us, too. In Rails 5.1.5, an isolation conflict produces

```
ArgumentError
wrong number of arguments (given 2, expected 0..1)
  app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.5/lib/active_record/errors.rb:98:in `initialize'
  app/vendor/bundle/ruby/2.3.0/gems/transaction_isolation-1.0.3/lib/transaction_isolation/active_record/connection_adapters/postgresql_adapter.rb:57:in `new'
  app/vendor/bundle/ruby/2.3.0/gems/transaction_isolation-1.0.3/lib/transaction_isolation/active_record/connection_adapters/postgresql_adapter.rb:57:in `translate_exception_with_transaction_isolation_conflict'
```
.

**Comment by joevandyk** [comment]
I emailed @qertoip a while ago and never got any response. I think we’ll need to fork/rename this and the isolation repo (or combine them into a single one).

**Comment by qertoip** [comment]
However, I published a new version:
https://rubygems.org/gems/transaction_isolation

Please let me know if that helps.
